# -*- coding: utf-8 -*-
"""Oklid_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Acv4Ghh31PpnlqtUAqgA-AYzWGziwTEP
"""

import math

def euclidean_distance(point1, point2):
    "İki nokta arasındaki Öklid mesafesini hesaplar."
    x1, y1 = point1
    x2, y2 = point2
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

def find_minimum_distance(points):
    "Listedeki noktalar arasındaki minimum mesafeyi bulur."
    distances = []
    for i in range(len(points)):
        for j in range(i+1, len(points)):
            distance = euclidean_distance(points[i], points[j])
            distances.append(distance)
    return min(distances)

def main():

    # Örnek noktalar
    points = [(2, 3), (5, 7), (1, 9), (4, 6), (8, 2)]

    # Minimum mesafeyi bul
    min_distance = find_minimum_distance(points)

    # Sonucu yazdır
    print("Minimum mesafe:", min_distance)

if __name__ == "__main__":
    main()